backend:
  name: github
  branch: master
  site_domain: https://quirky-carson-8d4332.netlify.app
  api_root: https://api.github.com
  base_url: https://api.netlify.com
  auth_endpoint: auth
  repo: podenborg/levelup-pro-gatsby

media_folder: static/assets

collections:
  - name: post
    label: Post
    folder: src/posts
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Created At, widget: date }
      - { name: body, label: Post, widget: markdown }
      - { name: image, label: Image, widget: image }